name: Test
# This workflow is triggered on pushes to the repository.
on: 
  pull_request:
    branches:
      - master


jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      # This step prints an output (time) from the previous step's action.
      - name: build and test
        run: |
          npm install
          npm run build
          npm test
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
